/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;


import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author DIOS
 */
public class VentanaJuego extends javax.swing.JFrame {
    boolean comienzoPartida = false;
    boolean comienzaContador = false;
    boolean gameOver = false;
    boolean comienzoJuego = false;
    Pajaro miPajaro = new Pajaro(50, Color.green);
    Obstaculos miObstaculos = new Obstaculos(ANCHOPANTALLA*2, ANCHOPANTALLA);
     Obstaculos miObstaculos2= new Obstaculos(ANCHOPANTALLA*2, 7*SEPARACION_COLUMNAS+ANCHOPANTALLA);
    
    static int ANCHOPANTALLA = 710;
    static int ALTOPANTALLA = 450;
    static int SEPARACION_COLUMNAS = 32;
    
    // ancho columna le damos el mismo  valor que en Columna.
    int ancho_columna = 35;
 
    Columna [] misColumnas = new Columna[24];
    BufferedImage buffer = null;
    Graphics2D bufferGraphics, lienzoGraphics = null;
    Temporizador miTemporizador = new Temporizador();
    int segundosTemporizdor = 0;
    
    String [] listaDePalabras ;
    
    int contador = 0;
    Timer temporizador = new Timer(10,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
            bucleDelJuego();
        }
    });
    
    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
        relojAnimacion.setVisible(false);
        this.setLocationRelativeTo(null);
        inicializaBuffers();
        //Damos las dimensiones a las ventanas de los menus
        ventanaInicio.setSize(712, 560);
        ventanaInicio.setLocationRelativeTo(null);
        ventanaGameOver.setSize(712, 560);
        ventanaGameOver.setLocationRelativeTo(null);
        ventanaEstorbo.setSize(425, 345);
        ventanaEstorbo.setLocationRelativeTo(null);
        System.out.println(texto);
        // Creamos un FOR para añadir  todas las columnas que forman las paredes.
        for ( int i = 0; i < misColumnas.length; i++){
                                //Añadimos "ANCHOPANTALLA/2" para que aparezca en mitad de pantalla el inicio.
           misColumnas [i] = new Columna(i*SEPARACION_COLUMNAS +ANCHOPANTALLA/2, ANCHOPANTALLA);
        }
        temporizador.start();
       
        
    }
   

    
    private void inicializaBuffers(){
        lienzoGraphics = (Graphics2D) texto.getGraphics();
        buffer = (BufferedImage) texto.createImage(ANCHOPANTALLA, ALTOPANTALLA);
        bufferGraphics = buffer.createGraphics();
        bufferGraphics.setColor(Color.BLACK);
        bufferGraphics.fillRect(0, 0, ANCHOPANTALLA, ALTOPANTALLA);
    }
   
    private void bucleDelJuego(){

        
        //contador de tiempo
      panelTemporizador.setText(Integer.toString(miTemporizador.getSegundos()));
        if (comienzoJuego == false){ 
            ventanaInicio.setVisible(true);
            temporizador.stop();
        }
        
 
        

        bufferGraphics.setColor(Color.BLACK);
        bufferGraphics.fillRect(0, 0, ANCHOPANTALLA, ALTOPANTALLA);
        
         //Chequea el suelo y el techo
        for (int i = 0; i < misColumnas.length; i++){
        if (miPajaro.chequeaColision(misColumnas[i])){
            temporizador.stop();
            ventanaGameOver.setVisible(true);
            miTemporizador.Detener();
            panelTiempoPerdido.setText(Integer.toString(miTemporizador.getSegundos()));
            relojAnimacion.setVisible(false);
         }
        }
        
        
        // Chequea a los PACMAN    
        if (miPajaro.chequeaColision2(miObstaculos) || (miPajaro.chequeaColision2(miObstaculos2))){
            temporizador.stop();
            ventanaGameOver.setVisible(true);
            miTemporizador.Detener();
            panelTiempoPerdido.setText(Integer.toString(miTemporizador.getSegundos()));
            relojAnimacion.setVisible(false);
         }
        
        
        
        for (int j = 0; j < misColumnas.length; j++){
            misColumnas[j].mueve(bufferGraphics);
        }
        
        miObstaculos.mueve(bufferGraphics);
        //dibujo el pájaro en su nueva posición
        miPajaro.mueve(bufferGraphics);
        lienzoGraphics.drawImage(buffer, 0,0, null);
        
       
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaGameOver = new javax.swing.JDialog();
        botonReiniciar = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panelTiempoPerdido = new javax.swing.JLabel();
        ventanaInicio = new javax.swing.JDialog();
        botonJugar = new javax.swing.JButton();
        botonExit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ventanaEstorbo = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estorboSI = new javax.swing.JButton();
        estorboNO = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        texto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelTemporizador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        frasesAleatorias = new javax.swing.JLabel();
        relojAnimacion = new javax.swing.JLabel();

        ventanaGameOver.setBackground(new java.awt.Color(255, 255, 255));
        ventanaGameOver.setResizable(false);

        botonReiniciar.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        botonReiniciar.setText("Reiniciar");
        botonReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonReiniciarMousePressed(evt);
            }
        });
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GameOver.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("El tiempo que perdiste jugando es:");

        jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.orange, null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0))));

        panelTiempoPerdido.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        panelTiempoPerdido.setForeground(new java.awt.Color(204, 102, 0));
        panelTiempoPerdido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTiempoPerdido.setText("00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(panelTiempoPerdido, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(panelTiempoPerdido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaGameOverLayout = new javax.swing.GroupLayout(ventanaGameOver.getContentPane());
        ventanaGameOver.getContentPane().setLayout(ventanaGameOverLayout);
        ventanaGameOverLayout.setHorizontalGroup(
            ventanaGameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaGameOverLayout.createSequentialGroup()
                .addGroup(ventanaGameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ventanaGameOverLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ventanaGameOverLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        ventanaGameOverLayout.setVerticalGroup(
            ventanaGameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaGameOverLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ventanaGameOverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(botonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        ventanaInicio.setResizable(false);
        ventanaInicio.getContentPane().setLayout(null);

        botonJugar.setText("Jugar");
        botonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonJugarMousePressed(evt);
            }
        });
        ventanaInicio.getContentPane().add(botonJugar);
        botonJugar.setBounds(310, 180, 142, 54);

        botonExit.setText("Salir Para siempre de esta M....");
        botonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonExitMousePressed(evt);
            }
        });
        ventanaInicio.getContentPane().add(botonExit);
        botonExit.setBounds(463, 517, 243, 32);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaperarcade.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        ventanaInicio.getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 710, 560);

        jLabel5.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seguro Que Quieres Salir?");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caution.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caution.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caution.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caution.png"))); // NOI18N

        estorboSI.setFont(new java.awt.Font("Phosphate", 1, 5)); // NOI18N
        estorboSI.setText("Si");
        estorboSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estorboSIMousePressed(evt);
            }
        });

        estorboNO.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        estorboNO.setText("NO (Gracias)");
        estorboNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estorboNOMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ventanaEstorboLayout = new javax.swing.GroupLayout(ventanaEstorbo.getContentPane());
        ventanaEstorbo.getContentPane().setLayout(ventanaEstorboLayout);
        ventanaEstorboLayout.setHorizontalGroup(
            ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEstorboLayout.createSequentialGroup()
                .addGroup(ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaEstorboLayout.createSequentialGroup()
                        .addGroup(ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaEstorboLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel5))
                            .addGroup(ventanaEstorboLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(ventanaEstorboLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
            .addGroup(ventanaEstorboLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(estorboSI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estorboNO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaEstorboLayout.setVerticalGroup(
            ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEstorboLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaEstorboLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estorboNO)
                        .addGap(48, 48, 48))
                    .addGroup(ventanaEstorboLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(estorboSI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)))
                .addGroup(ventanaEstorboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout textoLayout = new javax.swing.GroupLayout(texto);
        texto.setLayout(textoLayout);
        textoLayout.setHorizontalGroup(
            textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        textoLayout.setVerticalGroup(
            textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.red, null, java.awt.Color.red));

        panelTemporizador.setBackground(new java.awt.Color(102, 102, 102));
        panelTemporizador.setFont(new java.awt.Font("Phosphate", 1, 18)); // NOI18N
        panelTemporizador.setForeground(new java.awt.Color(204, 0, 0));
        panelTemporizador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTemporizador.setText("00");

        jLabel4.setFont(new java.awt.Font("Phosphate", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Seg");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        jLabel2.setFont(new java.awt.Font("Phosphate", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("TIEMPO:");

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(235, 84, 34)));

        frasesAleatorias.setFont(new java.awt.Font("Phosphate", 1, 18)); // NOI18N
        frasesAleatorias.setForeground(new java.awt.Color(204, 0, 0));
        frasesAleatorias.setText("--");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frasesAleatorias, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frasesAleatorias, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        relojAnimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reloj.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relojAnimacion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relojAnimacion)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        ///Mensajes emocionales con cada pulsacion de Espacio
        listaDePalabras = new String[] {"Animo","Venga que puedes","Eres el mejor","Vamos Vamos Vamos","El puto amo"}; 
        Random aleatorio = new Random();
        int posicionElegida = aleatorio.nextInt( listaDePalabras.length);
        frasesAleatorias.setText(listaDePalabras[posicionElegida]);
        
        
        
        
        if (evt.getKeyCode() == KeyEvent.VK_SPACE){
           // Velocidad que sube el pajaro con  el ESPACIO
           miPajaro.yVelocidad += 8;
           temporizador.restart();
           relojAnimacion.setVisible(true);
          if(comienzaContador == true){
                miTemporizador.Contar();
                comienzaContador = false;
       }
          
        }
           // Velocidad que sube el pajaro con  el ENTER
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           miPajaro.yVelocidad += 15;
       }
    }//GEN-LAST:event_formKeyPressed

    //Al pulsar reiniciar  mostraremos  un texto y recolocalremos las columnas y el pajaro.
    private void botonReiniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReiniciarMousePressed
        ventanaGameOver.setVisible(false);
        bufferGraphics.setColor(Color.black);
        bufferGraphics.fillRect(0, 0, ANCHOPANTALLA, ALTOPANTALLA);
        
        for ( int i = 0; i < misColumnas.length; i++){
                         //Añadimos "ANCHOPANTALLA/2" para que aparezca en mitad de pantalla el inicio.
           misColumnas [i] = new Columna(i*ancho_columna +ANCHOPANTALLA/2, ANCHOPANTALLA);
        }
        
        miPajaro = new Pajaro(30, Color.green);
        miPajaro.mueve(bufferGraphics);
        bufferGraphics.setColor(Color.white);
        bufferGraphics.setFont(new Font("Phosphate", Font.BOLD, 30)); 
        bufferGraphics.drawString("Pulsa espacio para continuar", 100, 200);
        lienzoGraphics.drawImage(buffer, 0, 0, null);
        comienzaContador = true;
    }//GEN-LAST:event_botonReiniciarMousePressed

    private void botonJugarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMousePressed
        bufferGraphics.setColor(Color.white);
        bufferGraphics.setFont(new Font("Phosphate", Font.BOLD, 30)); 
        bufferGraphics.drawString("Pulsa espacio para empezar", 100, 200);
        lienzoGraphics.drawImage(buffer, 0, 0, null);
        comienzoJuego= true;
        ventanaInicio.setVisible(false);
        comienzaContador = true;
        
    }//GEN-LAST:event_botonJugarMousePressed

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReiniciarActionPerformed

    private void botonExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMousePressed
       ventanaEstorbo.setVisible(true);
       
    }//GEN-LAST:event_botonExitMousePressed

    private void estorboSIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estorboSIMousePressed
      System.exit(0);
    }//GEN-LAST:event_estorboSIMousePressed

    private void estorboNOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estorboNOMousePressed
        ventanaEstorbo.setVisible(false);
    }//GEN-LAST:event_estorboNOMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExit;
    private javax.swing.JButton botonJugar;
    private javax.swing.JToggleButton botonReiniciar;
    private javax.swing.JButton estorboNO;
    private javax.swing.JButton estorboSI;
    private javax.swing.JLabel frasesAleatorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel panelTemporizador;
    private javax.swing.JLabel panelTiempoPerdido;
    private javax.swing.JLabel relojAnimacion;
    private javax.swing.JPanel texto;
    private javax.swing.JDialog ventanaEstorbo;
    private javax.swing.JDialog ventanaGameOver;
    private javax.swing.JDialog ventanaInicio;
    // End of variables declaration//GEN-END:variables
}
